$prevPwd = $PWD; Set-Location -ErrorAction Stop -LiteralPath $PSScriptRoot

. ./../../../infrastructure/scripts/create-appSettings.ps1

$APPCONFIG_NAME = "apetitoAppSettings-development"; # "apetitoAppSettings-staging" | "apetitoAppSettings" 
$KEYVAULT_NAME = "apetitoKeyVault-dev"; # "apetitoKeyVault-staging" | "apetitoKeyVault" 

CreateSecret "apetito:meinapetito:order:dbconnectionstring" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:orders:dbconnectionstring" '"<Value omitted>"'
CreateSetting "apetito:meinapetito:portal:api:ArticlePartsUrls:AllergenBaseUrl" '"https://www.cdn.apetito.de/mediaindex/Artikel/Icons/Allergenes"'
CreateSetting "apetito:meinapetito:portal:api:ArticlePartsUrls:EyeCatcherBaseUrl" '"https://www.cdn.apetito.de/mediaindex/Artikel/Icons/Stoerer"'
CreateSetting "apetito:meinapetito:portal:api:ArticlePartsUrls:SealBaseUrl" '"https://www.cdn.apetito.de/mediaindex/Artikel/Icons/Seals"'
CreateSetting "apetito:meinapetito:portal:api:ArticlePartsUrls:SupportedExtensions" '"[\"svg\"]"'
CreateSecret "apetito:meinapetito:portal:api:AzureADB2C:AppRegistration:PortalManagement:ClientID" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:portal:api:AzureADB2C:AppRegistration:PortalManagement:ClientSecret" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:portal:api:AzureADB2C:Domain" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:portal:api:AzureADB2C:PostRegistrationWebhook:Secret" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:portal:api:AzureADB2C:TenantID" '"<Value omitted>"'
CreateSetting "apetito:meinapetito:portal:api:AzureAd" '"{\"Tenant\": \"apetitoadb2cdevelopment.onmicrosoft.com\",\"Authority\": \"https://apetitoadb2cdevelopment.b2clogin.com/apetitoadb2cdevelopment.onmicrosoft.com/B2C_1_adb2cdevelopmentsignupandin\",\"AuthorityImpersonation\": \"https://apetitoadb2cdevelopment.b2clogin.com/apetitoadb2cdevelopment.onmicrosoft.com/B2C_1A_IMPERSONATION\",\"ClientId\": \"73af2c0f-929d-44f8-b7ff-ff9aaae7a874\"}"'
CreateSecret "apetito:meinapetito:portal:api:ConnectionStrings:DistributedCache" '"<Value omitted>"'
CreateSetting "apetito:meinapetito:portal:api:ConnectionStrings:PortalDb" '"Server=tcp:developmentmeinapetitosqlserver.database.windows.net,1433;Initial Catalog=PortalDb;Persist Security Info=False;User ID={0};Password={1};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"'
CreateSetting "apetito:meinapetito:portal:api:CustomerAzureFunction" '"{\"BaseAddress\" : \"https://apetito-retrieve-customer-azure-function-development.azurewebsites.net\",\"Authorization\": {\"HeaderName\": \"x-functions-key\",\"HeaderValue\": \"UDEhiptiFaqyb4Dn7VuKdMXJM6mFhBR9Onmaq6grr3nDDtP4Yo1u0Q==\"}}"'
CreateSetting "apetito:meinapetito:portal:api:CustomersService:BaseAddress" '"https://prodapetitocustomersapi-development.azurewebsites.net"'
CreateSetting "apetito:meinapetito:portal:api:Dashbaord:Prismic:Documents:RemnantsSliderId" '"YXgD8hcAAC8ABmBp"'
CreateSetting "apetito:meinapetito:portal:api:DefaultPriceList" '"[{\"key\":\"de-DE\",\"value\":\"TK\"},{\"key\":\"nl-NL\",\"value\":\"HO\"},{\"key\":\"de-AT\",\"value\":\"OT\"}]"'
CreateSetting "apetito:meinapetito:portal:api:Downloads:Prismic:CategoryDocumentTypeName" '"download_kategorien"'
CreateSetting "apetito:meinapetito:portal:api:Downloads:Prismic:DocumentTypeName" '"download_dokumente"'
CreateSetting "apetito:meinapetito:portal:api:Downloads:Prismic:FileBaseUrl" '"https://meinapetito-development.cdn.prismic.io/meinapetito-development/"'
CreateSetting "apetito:meinapetito:portal:api:Downloads:Prismic:OrderSystemMapping" '"[{\"Key\":\"Menü Service Manager\", \"Value\":\"MSM\"},{\"Key\":\"Ibs SC\", \"Value\":\"IB1\"},{\"Key\":\"Menüplaner\", \"Value\":\"MPN\"}]"'
CreateSetting "apetito:meinapetito:portal:api:Downloads:Prismic:WebhookSecret" '"<value omitted>"'
CreateSetting "apetito:meinapetito:portal:api:EMailTemplates:Invitation:PrismicDocumentType" '"e-mail-template_benutzer-einladung"'
CreateSetting "apetito:meinapetito:portal:api:Email:ApetitoNotificationBaseUrl" '"http://notification-api"'
CreateSetting "apetito:meinapetito:portal:api:Email:ChannelType" '"SENDGRID"'
CreateSetting "apetito:meinapetito:portal:api:Email:EventName" '"SendMeinApetitoInvitationMail"'
CreateSetting "apetito:meinapetito:portal:api:Email:InvitationSenderEmailAddress" '"mein-apetito@apebs.de"'
CreateSetting "apetito:meinapetito:portal:api:Faqs:Prismic:GroupDocumentType" '"help_group"'
CreateSetting "apetito:meinapetito:portal:api:Faqs:Prismic:SortOrderDocumentType" '"help_sort_order"'
CreateSetting "apetito:meinapetito:portal:api:Faqs:Prismic:TopicDocumentType" '"help_topic"'
CreateSetting "apetito:meinapetito:portal:api:Faqs:Prismic:TopicsSortOrderDocumentType" '"help_topic_sort_order"'
CreateSetting "apetito:meinapetito:portal:api:Faqs:Prismic:WebhookSecret" '"<value omitted>"'
CreateSetting "apetito:meinapetito:portal:api:ForbiddenArticlePrefixCollection" '"[\"EZ\",\"D\",\"B\",\"L\",\"H\",\"P\",\"SCH\",\"GJ\",\"A\"]"'
CreateSetting "apetito:meinapetito:portal:api:GraphQL" '"{\"PlaygroundgraphQlEndpointPath\": \"/graphql\",\"GraphQlEndpointPath\": \"/graphql\",\"PlaygroundApiPath\": \"/playground\"}"'
CreateSetting "apetito:meinapetito:portal:api:Greeting" '"Guten Morgen!!"'
CreateSetting "apetito:meinapetito:portal:api:LanguagesWithArticleGatewayLanguagesMap" '"[{\"key\":\"de-DE\", \"value\":\"D\"},{\"key\":\"de-AT\", \"value\":\"A\"},{\"key\":\"nl-NL\", \"value\":\"N\"},{\"key\":\"en-GB\", \"value\":\"E\"},{\"key\":\"es-ES\", \"value\":\"S\"}]"'
CreateSetting "apetito:meinapetito:portal:api:News:Prismic:CategoryDocumentTypeName" '"articel_category"'
CreateSetting "apetito:meinapetito:portal:api:News:Prismic:DocumentTypeName" '"news"'
CreateSetting "apetito:meinapetito:portal:api:PermissionsBaseAddress" '"https://api.apetito.de/authorization/"'
CreateSecret "apetito:meinapetito:portal:api:PortalDb:SqlUser" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:portal:api:PortalDb:SqlUserPassword" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:portal:api:Prismic:AccessToken" '"<Value omitted>"'
CreateSetting "apetito:meinapetito:portal:api:Prismic:Endpoint" '"https://meinapetito-development.prismic.io/api/v1"'
CreateSecret "apetito:meinapetito:portal:api:Prismic:Webhook:Secret" '"<Value omitted>"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:ApetitoArticleGatewayApi:Address" '"https://api.apetito.de/articlegateway/"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:ApetitoIProdaApi:Address" '"https://api.apetito.de/article/iproda/"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:ForbiddenArticlePrefix" '"[\"EZ\",\"D\",\"B\",\"L\",\"H\",\"P\",\"SCH\",\"GJ\",\"A\"]"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:MaterialSortiment:Prefix" '"WM"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:MaterialSortimentTypeCode" '"WERBEMITTEL"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:MeinApetitoApi:Address" '"https://staging.meinapetito.de/api/"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:PhotoBuilder:MaterialImageBaseUrlRectangular" '"https://www.apetito-menues.de/media_index/Material/;https://www.apetito-menues.de/media_index/Artikel/meinapetito/gross/;https://www.apetito-menues.de/mediaport/meinapetito_Produktsuche_176x120/;https://www.apetito-menues.de/media_index/Artikel/meinapetito/gross/"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:PhotoBuilder:MaterialImageBaseUrlSquare" '"https://www.apetito-menues.de/media_index/Material/;https://www.apetito-menues.de/media_index/Artikel/meinapetito/gross/;https://www.apetito-menues.de/mediaport/meinapetito_Produktsuche_176x120/;https://www.apetito-menues.de/media_index/Artikel/meinapetito/gross/"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:PhotoBuilder:MaterialImagePath" '"https://www.apetito-menues.de/mediaport/meinapetito_Produktsuche_{0}/{1}.jpg"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:PhotoBuilder:NutriScoreImagePath" '"https://www.apetito-menues.de/media_index/Artikel/nutriscore/svg/border/NutriScore{0}_B.svg"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:PhotoBuilder:ProductImageBaseUrlRectangular" '"https://www.apetito-menues.de/mediaport/mylunch_Produktsuche_600x600/;https://www.apetito-menues.de/mediaport/mylunch_Speiseplan_300x300/;https://www.apetito-menues.de/media_index/Artikel/meinapetito/gross/"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:PhotoBuilder:ProductImageBaseUrlSquare" '"https://www.apetito-menues.de/mediaport/mylunch_Produktsuche_600x600/;https://www.apetito-menues.de/mediaport/mylunch_Speiseplan_300x300/;https://www.apetito-menues.de/media_index/Artikel/meinapetito/gross/"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:PhotoBuilder:ProductImagePath" '"https://www.apetito-menues.de/mediaport/mylunch_Speiseplan_{0}/"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:PhotoBuilder:ProductImagePath:Big" '"https://www.apetito-menues.de/mediaport/mylunch_Produktsuche_600x600/"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:PhotoBuilder:ProductImagePath:Middle" '"https://www.apetito-menues.de/mediaport/mylunch_Speiseplan_300x300/"'
CreateSetting "apetito:meinapetito:portal:api:ProductCatalog:PhotoBuilder:ProductImagePath:Small" '""'
CreateSetting "apetito:meinapetito:portal:api:SupportedLanguages" '"[\"de-DE\",\"nl-NL\",\"de-AT\",\"es-ES\"]"'
CreateSecret "apetito:meinapetito:portal:api:UserAccessToken:BearerToken:Issuer" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:portal:api:UserAccessToken:BearerToken:Secret" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:portal:api:UserAccessToken:IbsscToken:Secret" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:portal:api:root:orders:AddApetitoOrder" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:portal:api:root:orders:RetrieveApetitoOrders:ApiKey" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:webhooks:azureadb2c:api:AzureADB2C:AppRegistration:PortalApi:ObjectId" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:webhooks:azureadb2c:api:AzureADB2C:AppRegistration:PortalManagement:ClientID" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:webhooks:azureadb2c:api:AzureADB2C:AppRegistration:PortalManagement:ClientSecret" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:webhooks:azureadb2c:api:AzureADB2C:Domain" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:webhooks:azureadb2c:api:AzureADB2C:TenantID" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:webhooks:azureadb2c:api:meinapetito:secret" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:webhooks:prismic:api:AzureADB2C:AppRegistration:PortalApi:ObjectId" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:webhooks:prismic:api:AzureADB2C:AppRegistration:PortalManagement:ClientID" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:webhooks:prismic:api:AzureADB2C:AppRegistration:PortalManagement:ClientSecret" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:webhooks:prismic:api:AzureADB2C:Domain" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:webhooks:prismic:api:AzureADB2C:TenantID" '"<Value omitted>"'
CreateSecret "apetito:meinapetito:webhooks:prismic:api:meinapetito:secret" '"<Value omitted>"'

$prevPwd | Set-Location